(cl:in-package #:consecution)

(defmacro with-key-function ((name key) &body body)
  (alx:with-gensyms (f)
    (alx:once-only (key)
      `(let ((,f (if (null ,key) nil (function-designator-function ,key))))
         (declare (type (or function null) ,f))
         (flet ((,name (x) (if (null ,f) x (funcall ,f x))))
           (declare (inline ,name))
           ,@body)))))
