(in-package #:consecution-extrinsic/test)

(defun test ()
  (let ((system (asdf:find-system :consecution-extrinsic/test)))
    (ansi-test-harness:ansi-test
     :exit t
     :directory (merge-pathnames (make-pathname
                                  :directory '(:relative "dependencies" "ansi-test"))
                                 (asdf:component-pathname system))
     :extrinsic-symbols '(consecution:copy-seq
                          consecution:elt
                          consecution:fill
                          consecution:make-sequence
                          consecution:subseq
                          consecution:map-into
                          consecution:map
                          consecution:reduce
                          consecution:count
                          consecution:count-if
                          consecution:count-if-not
                          consecution:length
                          consecution:reverse
                          consecution:nreverse
                          consecution:sort
                          consecution:stable-sort
                          consecution:find
                          consecution:find-if
                          consecution:find-if-not
                          consecution:position
                          consecution:position-if
                          consecution:position-if-not
                          consecution:search
                          consecution:mismatch
                          consecution:replace
                          consecution:substitute
                          consecution:substitute-if
                          consecution:substitute-if-not
                          consecution:nsubstitute
                          consecution:nsubstitute-if
                          consecution:nsubstitute-if-not
                          consecution:concatenate
                          consecution:merge
                          consecution:remove
                          consecution:remove-if
                          consecution:remove-if-not
                          consecution:delete
                          consecution:delete-if
                          consecution:delete-if-not
                          consecution:remove-duplicates
                          consecution:delete-duplicates)
     :tests '("ARRAY-FILL-"
              "ARRAY-FIXNUM-FILL-"
              "ARRAY-STRING-FILL."
              "ARRAY-UNSIGNED-BYTE8-FILL-"
              "CONCATENATE."
              "COPY-SEQ."
              "COUNT"
              "DELETE-BIT-VECTOR."
              "DELETE-DUPLICATES."
              "DELETE-IF"
              "DELETE-LIST."
              "DELETE-RANDOM"
              "DELETE-STRING."
              "DELETE-VECTOR."
              "DELETE."
              "ELT"
              "FILL."
              "FIND-BIT-VECTOR."
              "FIND-IF-BIT-VECTOR."
              "FIND-IF-LIST."
              "FIND-IF-NOT-BIT-VECTOR."
              "FIND-IF-NOT-LIST."
              "FIND-IF-NOT-STRING."
              "FIND-IF-NOT-VECTOR."
              "FIND-IF-NOT."
              "FIND-IF-STRING."
              "FIND-IF-VECTOR."
              "FIND-IF."
              "FIND-LIST."
              "FIND-STRING."
              "FIND-VECTOR."
              "FIND."
              "GREP: ."
              "MAKE-SEQUENCE."
              "MAP-ARRAY."
              "MAP-BIT-VECTOR."
              "MAP-CONS."
              "MAP-INTO-ARRAY."
              "MAP-INTO-LIST."
              "MAP-INTO-STRING."
              "MAP-INTO."
              "MAP-NIL."
              "MAP-NULL."
              "MAP-STRING."
              "MAP."
              "MERGE-BIT-VECTOR-LENGTH."
              "MERGE-BIT-VECTOR."
              "MERGE-CONS."
              "MERGE-LIST."
              "MERGE-NULL."
              "MERGE-STRING."
              "MERGE-VECTOR-LENGTH."
              "MERGE-VECTOR."
              "MERGE."
              "MISMATCH-BIT-VECTOR."
              "MISMATCH-LIST."
              "MISMATCH-STRING."
              "MISMATCH-VECTOR."
              "MISMATCH."
              "MISTMATCH-STRING."
              "NREVERSE-BIT-VECTOR."
              "NREVERSE-LIST."
              "NREVERSE-STRING."
              "NREVERSE-VECTOR."
              "NREVERSE."
              "NSUBSTITUTE-BIT-VECTOR."
              "NSUBSTITUTE-IF-BIT-VECTOR."
              "NSUBSTITUTE-IF-LIST."
              "NSUBSTITUTE-IF-NOT-BIT-VECTOR."
              "NSUBSTITUTE-IF-NOT-LIST."
              "NSUBSTITUTE-IF-NOT-STRING."
              "NSUBSTITUTE-IF-NOT-VECTOR."
              "NSUBSTITUTE-IF-NOT."
              "NSUBSTITUTE-IF-STRING."
              "NSUBSTITUTE-IF-VECTOR."
              "NSUBSTITUTE-IF."
              "NSUBSTITUTE-LIST."
              "NSUBSTITUTE-STRING."
              "NSUBSTITUTE-VECTOR."
              "NSUBSTITUTE."
              "POSITION-BIT-VECTOR."
              "POSITION-IF-BIT-VECTOR."
              "POSITION-IF-LIST."
              "POSITION-IF-NOT-BIT-VECTOR."
              "POSITION-IF-NOT-LIST."
              "POSITION-IF-NOT-STRING."
              "POSITION-IF-NOT-VECTOR."
              "POSITION-IF-NOT."
              "POSITION-IF-STRING."
              "POSITION-IF-VECTOR."
              "POSITION-IF."
              "POSITION-LIST."
              "POSITION-STRING."
              "POSITION-VECTOR."
              "POSITION."
              "RANDOM-DELETE-DUPLICATES"
              "RANDOM-REMOVE-DUPLICATES"
              "REDUCE-ARRAY."
              "REDUCE-BITSTRING."
              "REDUCE-LIST."
              "REDUCE-STRING."
              "REDUCE."
              "REMOVE-BIT-VECTOR."
              "REMOVE-DUPLICATES."
              "REMOVE-IF-LIST."
              "REMOVE-IF-NOT-LIST."
              "REMOVE-IF-NOT-RANDOM"
              "REMOVE-IF-NOT-STRING."
              "REMOVE-IF-NOT."
              "REMOVE-IF-RANDOM"
              "REMOVE-IF-STRING."
              "REMOVE-IF."
              "REMOVE-LIST."
              "REMOVE-RANDOM"
              "REMOVE-STRING."
              "REMOVE-VECTOR."
              "REMOVE."
              "REPLACE-BIT-VECTOR."
              "REPLACE-LIST."
              "REPLACE-STRING."
              "REPLACE-VECTOR."
              "REPLACE."
              "REVERSE-BIT-VECTOR."
              "REVERSE-LIST."
              "REVERSE-STRING."
              "REVERSE-VECTOR."
              "REVERSE."
              "SEARCH-BITVECTOR."
              "SEARCH-LIST."
              "SEARCH-STRING."
              "SEARCH-VECTOR."
              "SEARCH."
              "SORT"
              "STABLE-SORT"
              "SUBSEQ"
              "SUBSTITUTE"))))
